### PR TITLE
Configure

### PR DESCRIPTION
**Pull request by ghost**
Hello. I am your best friend, Seol So.

In this project, it has only 3 files in `root directory`. But, it is not a good design pattern. You have to create the all of the sources of this project in `src` folder because of all of the project in the world require many kinds of files such as `README.md` or `package.json` or prettier and eslint configuration files that project require. And then, this is why we have to create files in the `src` folder.

Next, I add some configuration files. Prettier and Eslint is for checking the syntax and making more prettier then before. So, Before you commit, please run `yarn run format` or `npm run format` to format all of the sources.

Lastly, I separated many html, css and javascript files in `src` folder. And then, I think that you have to set the `root directory` to deploy as `src/pages/`. Because I moved index.html to `src/pages/` and the deploy service will configure it if you set. In case of css, you can create many kind of css files. If you want to add some of styles to `screen`, go to `src/css/screens/` folder and create files. And You have to add `import` syntax to `src/css/styles.css` because of the structure that `index.html` import only `styles.css` file and `styles.css` file import all of the css files for components and screens.

### CODE REVIEW

**Comment by ghost** [comment]
Ah, and please add a description in `package.json` @akka-4 .

**Comment by ghost** [comment]
Please check this pull request and merge it if you like it. And you can ask something about this pull request in this pull request if you have some questions.

**Comment by akka-4** [comment]
hi
i'm jae yoon.
I invited you to be a collaborator on this project. So, you will be able to edit or check the files!

Thanks for  teaching me a lot about Git-Hub! Right now, I don't know much about Git-Hub... so I'll have to study harder....

**Comment by ghost** [comment]
Thanks for accepting my pull request  but it is not Git-Hub. Lolol... it is GitHub. I just want to let you know this.

**Comment by akka-4** [comment]
Oh....okay....!!

**Pull request merged**
